"""models mini fix

Revision ID: 5cb09b489b14
Revises: abebe0b9f5e0
Create Date: 2025-07-15 11:13:49.745966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cb09b489b14'
down_revision: Union[str, Sequence[str], None] = 'abebe0b9f5e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('grade', sa.Float(), nullable=True))
    op.drop_column('reviews', 'rating')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('reviews', 'grade')
    # ### end Alembic commands ###
