"""Review model comment_data fix

Revision ID: aa098ccfbc9c
Revises: be3c30a2e273
Create Date: 2025-07-15 17:07:43.531322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa098ccfbc9c'
down_revision: Union[str, Sequence[str], None] = 'be3c30a2e273'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reviews', 'comment_date',
                    existing_type=sa.DateTime(),
                    server_default=sa.text('now()'),
                    existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reviews', 'comment_date',
                    existing_type=sa.DateTime(),
                    server_default=None,
                    existing_nullable=True)
    # ### end Alembic commands ###
